spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document-management-system
    username: postgres
    password: NewPost
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true

  profiles:
    active: development

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: WARN
    javax.management: WARN
    sun.rmi: WARN

server:
  port: 8082

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 20MB
